import type { Product } from "./store"

export interface Category {
  id: string;
  name: string;
  icon: string;
  image: string;
  description?: string; // Adding optional description
}

export const categories: Category[] = [
  { id: "marine", name: "Marine Fish", icon: "🐟", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/1.a352b412.png", description: "Freshly caught marine fish from the deep seas." },
  { id: "water", name: "Fresh Water", icon: "🐠", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/2.fd6a805f.png", description: "Delicious freshwater fish from local farms." },
  { id: "shell", name: "Shell Fish", icon: "🦐", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/3.c3488ae6.png", description: "A variety of shell fish, perfect for curries and stir-fries." },
  { id: "fry", name: "Fry Ready", icon: "🍳", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/4.64ecabe7.png", description: "Pre-marinated fish, ready to be fried to perfection." },
  { id: "combo", name: "Combo Packs", icon: "📦", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/5.45082f45.png", description: "Assorted seafood packs for a complete meal experience." },
  { id: "exotics", name: "Exotics", icon: "🦞", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/1.a352b412.png", description: "Premium exotic seafood delicacies from around the world." },
  { id: "chicken", name: "Chicken", icon: "🍗", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/2.fd6a805f.png", description: "Fresh chicken cuts and whole chicken." },
  { id: "mutton", name: "Mutton", icon: "🥩", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/3.c3488ae6.png", description: "Premium quality mutton and lamb." },
  { id: "eggs", name: "Eggs", icon: "🥚", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/4.64ecabe7.png", description: "Farm fresh eggs." },
  { id: "spices", name: "Spices", icon: "🌶️", image: "https://bayhawk.clientstagingdemo.com/_next/static/media/5.45082f45.png", description: "Authentic spices and masalas." },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Fresh Indian Salmon",
    price: 799,
    originalPrice: 999,
    image: "/Website Source Files/sample/2.jpg",
    category: "water",
    rating: 4.9,
    reviews: 312,
    weight: "500g",
    pieces: "2-3 pieces",
    serves: "2-3",
    description: "High-quality Indian Salmon, perfect for grilling and curries. A healthy and delicious choice.",
    inStock: true,
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Rohu Fish Large",
    price: 349,
    originalPrice: 449,
    image: "/Website Source Files/sample/3.jpg",
    category: "water",
    rating: 4.5,
    reviews: 456,
    weight: "1kg",
    pieces: "4-5 pieces",
    serves: "4-5",
    description: "Large size Rohu fish, ideal for family meals. Known for its rich flavor and soft texture.",
    inStock: true,
  },
  {
    id: "3",
    name: "Red Snapper",
    price: 599,
    originalPrice: 799,
    image: "/Website Source Files/sample/4.jpg",
    category: "marine",
    rating: 4.8,
    reviews: 234,
    weight: "750g",
    pieces: "1 whole fish",
    serves: "3-4",
    description: "Fresh Red Snapper, a delicacy in many cuisines. Its sweet, nutty flavor is a must-try.",
    inStock: true,
    badge: "Premium",
  },
  {
    id: "4",
    name: "Mackerel (Bangda)",
    price: 249,
    originalPrice: 349,
    image: "/Website Source Files/sample/5.jpg",
    category: "marine",
    rating: 4.7,
    reviews: 189,
    weight: "500g",
    pieces: "4-5 pieces",
    serves: "2-3",
    description: "Fresh Mackerel, rich in Omega-3. Perfect for frying or making a tangy curry.",
    inStock: true,
  },
  {
    id: "5",
    name: "Catla Fish Medium",
    price: 299,
    originalPrice: 399,
    image: "/Website Source Files/sample/6.jpg",
    category: "water",
    rating: 4.6,
    reviews: 145,
    weight: "800g",
    pieces: "3-4 pieces",
    serves: "3-4",
    description: "Medium-sized Catla fish, a popular choice for its taste and texture. Great for everyday meals.",
    inStock: true,
  },
  {
    id: "6",
    name: "Silver Pomfret",
    price: 699,
    originalPrice: 899,
    image: "/Website Source Files/sample/8.jpg",
    category: "marine",
    rating: 4.9,
    reviews: 312,
    weight: "500g",
    pieces: "2-3 pieces",
    serves: "2-3",
    description: "Premium Silver Pomfret, known for its delicate flavor and firm texture. A gourmet's delight.",
    inStock: true,
    badge: "Chef's Choice",
  },
  {
    id: "7",
    name: "Tilapia",
    price: 229,
    originalPrice: 299,
    image: "/Website Source Files/sample/9.jpg",
    category: "water",
    rating: 4.4,
    reviews: 278,
    weight: "1kg",
    pieces: "3-4 pieces",
    serves: "4-5",
    description: "Fresh Tilapia, a versatile fish that can be cooked in various ways. Mild flavor and easy to cook.",
    inStock: true,
  },
  {
    id: "8",
    name: "Sardines",
    price: 199,
    originalPrice: 249,
    image: "/Website Source Files/sample/11.jpg",
    category: "marine",
    rating: 4.3,
    reviews: 167,
    weight: "500g",
    pieces: "10-12 pieces",
    serves: "2-3",
    description: "Fresh Sardines, packed with nutrients. Ideal for grilling or pan-frying.",
    inStock: true,
  },
  {
    id: "9",
    name: "Black Pomfret",
    price: 549,
    originalPrice: 699,
    image: "/Website Source Files/sample/12.jpg",
    category: "marine",
    rating: 4.7,
    reviews: 132,
    weight: "600g",
    pieces: "2 pieces",
    serves: "2-3",
    description: "Flavorful Black Pomfret, great for tandoori and baked preparations. A true delight for fish lovers.",
    inStock: true,
  },
  {
    id: "10",
    name: "Basa Fillet",
    price: 399,
    originalPrice: 499,
    image: "/Website Source Files/sample/2.jpg",
    category: "water",
    rating: 4.5,
    reviews: 112,
    weight: "500g",
    pieces: "2-3 fillets",
    serves: "2-3",
    description: "Boneless Basa fillets, perfect for a quick and healthy meal. Mild flavor and tender texture.",
    inStock: true,
    badge: "New Arrival",
  },
  {
    id: "11",
    name: "Fresh Lobster",
    price: 1899,
    originalPrice: 2299,
    image: "/Website Source Files/sample/2.jpg",
    category: "exotics",
    rating: 5.0,
    reviews: 89,
    weight: "800g",
    pieces: "1 whole lobster",
    serves: "2-3",
    description: "Premium fresh lobster, a luxurious delicacy. Perfect for special occasions and gourmet preparations.",
    inStock: true,
    badge: "Premium",
  },
  {
    id: "12",
    name: "King Crab Legs",
    price: 2499,
    originalPrice: 2999,
    image: "/Website Source Files/sample/3.jpg",
    category: "exotics",
    rating: 4.9,
    reviews: 67,
    weight: "1kg",
    pieces: "4-5 legs",
    serves: "3-4",
    description: "Succulent King Crab legs, sweet and tender meat. An exotic treat for seafood connoisseurs.",
    inStock: true,
    badge: "Exotic",
  },
  {
    id: "13",
    name: "Octopus",
    price: 1299,
    originalPrice: 1599,
    image: "/Website Source Files/sample/4.jpg",
    category: "exotics",
    rating: 4.7,
    reviews: 54,
    weight: "600g",
    pieces: "1 whole",
    serves: "2-3",
    description: "Fresh octopus, tender and flavorful. Ideal for Mediterranean and Asian cuisine preparations.",
    inStock: true,
    badge: "Chef's Choice",
  },
  {
    id: "14",
    name: "Chicken Breast Boneless",
    price: 299,
    originalPrice: 349,
    image: "/Website Source Files/sample/5.jpg",
    category: "chicken",
    rating: 4.8,
    reviews: 234,
    weight: "500g",
    pieces: "2 pieces",
    serves: "2-3",
    description: "Premium boneless chicken breast, perfect for grilling and curries.",
    inStock: true,
    badge: "Fresh",
  },
  {
    id: "15",
    name: "Chicken Curry Cut",
    price: 189,
    originalPrice: 229,
    image: "/Website Source Files/sample/6.jpg",
    category: "chicken",
    rating: 4.7,
    reviews: 456,
    weight: "500g",
    pieces: "8-10 pieces",
    serves: "3-4",
    description: "Fresh chicken curry cut with bone, ideal for traditional curries.",
    inStock: true,
  },
  {
    id: "16",
    name: "Whole Chicken",
    price: 349,
    originalPrice: 399,
    image: "/Website Source Files/sample/7.jpg",
    category: "chicken",
    rating: 4.9,
    reviews: 189,
    weight: "1kg",
    pieces: "1 whole",
    serves: "4-5",
    description: "Farm fresh whole chicken, cleaned and ready to cook.",
    inStock: true,
    badge: "Best Seller",
  },
  {
    id: "17",
    name: "Mutton Curry Cut",
    price: 649,
    originalPrice: 749,
    image: "/Website Source Files/sample/8.jpg",
    category: "mutton",
    rating: 4.8,
    reviews: 167,
    weight: "500g",
    pieces: "6-8 pieces",
    serves: "2-3",
    description: "Premium mutton curry cut with bone, perfect for rich curries.",
    inStock: true,
    badge: "Premium",
  },
  {
    id: "18",
    name: "Mutton Boneless",
    price: 749,
    originalPrice: 849,
    image: "/Website Source Files/sample/9.jpg",
    category: "mutton",
    rating: 4.7,
    reviews: 134,
    weight: "500g",
    pieces: "Boneless chunks",
    serves: "2-3",
    description: "Tender boneless mutton, ideal for kebabs and biryanis.",
    inStock: true,
  },
  {
    id: "19",
    name: "Mutton Keema",
    price: 599,
    originalPrice: 699,
    image: "/Website Source Files/sample/10.jpg",
    category: "mutton",
    rating: 4.6,
    reviews: 98,
    weight: "500g",
    pieces: "Minced",
    serves: "3-4",
    description: "Fresh mutton keema, perfect for keema curry and parathas.",
    inStock: true,
  },
  {
    id: "20",
    name: "Farm Fresh Brown Eggs",
    price: 89,
    originalPrice: 99,
    image: "/Website Source Files/sample/11.jpg",
    category: "eggs",
    rating: 4.9,
    reviews: 567,
    weight: "6 pieces",
    pieces: "6 eggs",
    serves: "2-3",
    description: "Organic brown eggs from free-range chickens.",
    inStock: true,
    badge: "Organic",
  },
  {
    id: "21",
    name: "White Eggs Tray",
    price: 149,
    originalPrice: 169,
    image: "/Website Source Files/sample/12.jpg",
    category: "eggs",
    rating: 4.7,
    reviews: 423,
    weight: "12 pieces",
    pieces: "12 eggs",
    serves: "4-5",
    description: "Fresh white eggs, perfect for daily use.",
    inStock: true,
  },
  {
    id: "22",
    name: "Garam Masala Powder",
    price: 149,
    originalPrice: 179,
    image: "/Website Source Files/sample/13.jpg",
    category: "spices",
    rating: 4.8,
    reviews: 234,
    weight: "100g",
    pieces: "1 pack",
    serves: "Multiple uses",
    description: "Authentic garam masala blend for rich flavors.",
    inStock: true,
    badge: "Premium",
  },
  {
    id: "23",
    name: "Red Chilli Powder",
    price: 99,
    originalPrice: 119,
    image: "/Website Source Files/sample/2.jpg",
    category: "spices",
    rating: 4.7,
    reviews: 189,
    weight: "100g",
    pieces: "1 pack",
    serves: "Multiple uses",
    description: "Pure red chilli powder for authentic spice.",
    inStock: true,
  },
  {
    id: "24",
    name: "Turmeric Powder",
    price: 79,
    originalPrice: 99,
    image: "/Website Source Files/sample/3.jpg",
    category: "spices",
    rating: 4.9,
    reviews: 312,
    weight: "100g",
    pieces: "1 pack",
    serves: "Multiple uses",
    description: "Pure turmeric powder with natural color and aroma.",
    inStock: true,
    badge: "Pure",
  },
]

export const recipes = [
  {
    id: "1",
    name: "Goan Fish Curry",
    image: "/goan-fish-curry.jpg",
    time: "45 mins",
    difficulty: "Medium",
    ingredients: ["Pomfret 500g", "Coconut Milk", "Tamarind", "Red Chilies", "Garlic"],
    steps: [
      "Clean and marinate the fish with salt and turmeric",
      "Grind coconut with spices to make masala paste",
      "Cook the paste in oil until aromatic",
      "Add tamarind water and bring to boil",
      "Add fish pieces and simmer for 15 minutes",
    ],
    video: "https://example.com/video",
  },
  {
    id: "2",
    name: "Butter Garlic Prawns",
    image: "/butter-garlic-prawns.jpg",
    time: "25 mins",
    difficulty: "Easy",
    ingredients: ["Prawns 500g", "Butter", "Garlic", "Lemon", "Parsley"],
    steps: [
      "Clean and devein prawns",
      "Sauté garlic in butter until golden",
      "Add prawns and cook on high heat",
      "Season with salt, pepper, and lemon juice",
      "Garnish with fresh parsley",
    ],
    video: "https://example.com/video2",
  },
  {
    id: "3",
    name: "Bengali Fish Curry",
    image: "/bengali-fish-curry-mustard.jpg",
    time: "40 mins",
    difficulty: "Medium",
    ingredients: ["Rohu 500g", "Mustard Paste", "Green Chilies", "Turmeric", "Mustard Oil"],
    steps: [
      "Marinate fish with salt and turmeric",
      "Lightly fry the fish pieces",
      "Make a paste of mustard seeds",
      "Cook mustard paste in oil",
      "Add water, fish, and simmer until done",
    ],
    video: "https://example.com/video3",
  },
]

export const testimonials = [
  {
    id: "1",
    name: "Priya Sharma",
    avatar: "/indian-woman-portrait.png",
    rating: 5,
    text: "The quality of fish is amazing! Always fresh and delivered on time. My family loves the pomfret.",
    location: "Mumbai",
  },
  {
    id: "2",
    name: "Rahul Menon",
    avatar: "/indian-man-portrait.png",
    rating: 5,
    text: "Best prawns I have ever ordered online. Cleaned perfectly and tastes so fresh!",
    location: "Bangalore",
  },
  {
    id: "3",
    name: "Anjali Patel",
    avatar: "/indian-woman-smiling.png",
    rating: 4,
    text: "Great service and quality. The combo packs are perfect for family gatherings.",
    location: "Chennai",
  },
]

export const faqs = [
  {
    question: "How fresh is your seafood?",
    answer:
      "All our seafood is sourced directly from fishermen and delivered within 24-48 hours of catch. We maintain cold chain throughout the delivery process.",
  },
  {
    question: "What are your delivery timings?",
    answer: "We deliver between 7 AM to 9 PM. You can choose your preferred time slot during checkout.",
  },
  {
    question: "Do you offer cleaning services?",
    answer: "Yes! All our fish and seafood come cleaned and ready to cook. You can choose your preferred cut style.",
  },
  {
    question: "What is your return policy?",
    answer:
      "If you are not satisfied with the quality, we offer 100% refund or replacement. Just contact us within 2 hours of delivery.",
  },
  {
    question: "Which areas do you deliver to?",
    answer:
      "We currently deliver to all major cities including Mumbai, Delhi, Bangalore, Chennai, Kolkata, Hyderabad, and Pune.",
  },
]
