import type { Product } from "./store"

export const categories = [
  { id: "marine", name: "Marine Fish", icon: "🐟", image: "/marine-fish.jpg" },
  { id: "water", name: "Fresh Water", icon: "🐠", image: "/freshwater-fish.jpg" },
  { id: "shell", name: "Shell Fish", icon: "🦐", image: "/prawns-shrimp.jpg" },
  { id: "fry", name: "Fry Ready", icon: "🍳", image: "/fried-fish.jpg" },
  { id: "combo", name: "Combo Packs", icon: "📦", image: "/seafood-combo-pack.jpg" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Fresh Pomfret",
    price: 599,
    originalPrice: 799,
    image: "/fresh-pomfret-fish.jpg",
    category: "marine",
    rating: 4.8,
    reviews: 234,
    weight: "500g",
    pieces: "2-3 pieces",
    serves: "2-3",
    description: "Premium quality pomfret, freshly caught from the Arabian Sea. Perfect for frying or grilling.",
    inStock: true,
    badge: "Best Seller",
  },
  {
    id: "2",
    name: "Tiger Prawns",
    price: 749,
    originalPrice: 899,
    image: "/tiger-prawns.png",
    category: "shell",
    rating: 4.7,
    reviews: 189,
    weight: "500g",
    pieces: "15-20 pieces",
    serves: "3-4",
    description: "Jumbo tiger prawns, cleaned and deveined. Ready to cook delicious curries or grilled dishes.",
    inStock: true,
    badge: "Premium",
  },
  {
    id: "3",
    name: "Rohu Fish",
    price: 299,
    originalPrice: 399,
    image: "/rohu-fish.jpg",
    category: "water",
    rating: 4.5,
    reviews: 456,
    weight: "1kg",
    pieces: "4-5 pieces",
    serves: "4-5",
    description: "Fresh Rohu from clean water farms. Rich in protein and omega-3 fatty acids.",
    inStock: true,
  },
  {
    id: "4",
    name: "King Fish Steaks",
    price: 699,
    originalPrice: 850,
    image: "/king-fish-steaks.jpg",
    category: "marine",
    rating: 4.9,
    reviews: 312,
    weight: "500g",
    pieces: "4-5 steaks",
    serves: "2-3",
    description: "Premium king fish cut into perfect steaks. Ideal for grilling, frying, or making fish curry.",
    inStock: true,
    badge: "Chef's Choice",
  },
  {
    id: "5",
    name: "Crab Whole",
    price: 449,
    originalPrice: 599,
    image: "/whole-crab-seafood.jpg",
    category: "shell",
    rating: 4.6,
    reviews: 145,
    weight: "400g",
    pieces: "1 piece",
    serves: "2",
    description: "Fresh whole crab, perfect for making delicious crab masala or pepper crab.",
    inStock: true,
  },
  {
    id: "6",
    name: "Fish Fry Pack",
    price: 399,
    originalPrice: 499,
    image: "/fish-fry-ready-to-cook.jpg",
    category: "fry",
    rating: 4.4,
    reviews: 278,
    weight: "500g",
    pieces: "8-10 pieces",
    serves: "4",
    description: "Marinated and ready-to-fry fish pieces. Just heat oil and fry for 5 minutes.",
    inStock: true,
    badge: "Ready to Cook",
  },
  {
    id: "7",
    name: "Seafood Combo",
    price: 1299,
    originalPrice: 1599,
    image: "/seafood-combo-platter.jpg",
    category: "combo",
    rating: 4.8,
    reviews: 89,
    weight: "1.5kg",
    pieces: "Assorted",
    serves: "6-8",
    description: "Perfect family pack with prawns, fish fillets, and squid rings. Great value for parties.",
    inStock: true,
    badge: "Value Pack",
  },
  {
    id: "8",
    name: "Catla Fish",
    price: 349,
    originalPrice: 449,
    image: "/catla-fish.jpg",
    category: "water",
    rating: 4.3,
    reviews: 167,
    weight: "1kg",
    pieces: "4-5 pieces",
    serves: "4-5",
    description: "Fresh Catla fish, a Bengali favorite. Perfect for fish curry and steamed preparations.",
    inStock: false,
  },
  {
    id: "9",
    name: "Salmon Fillet",
    price: 899,
    originalPrice: 1199,
    image: "/salmon-fillet.jpg",
    category: "marine",
    rating: 4.9,
    reviews: 423,
    weight: "400g",
    pieces: "2 fillets",
    serves: "2-3",
    description: "Premium Atlantic salmon fillets, rich in omega-3. Perfect for grilling, baking, or pan-searing.",
    inStock: true,
    badge: "Imported",
  },
  {
    id: "10",
    name: "Mussels White",
    price: 299,
    originalPrice: 399,
    image: "/white-mussels.jpg",
    category: "shell",
    rating: 4.5,
    reviews: 198,
    weight: "500g",
    pieces: "25-30 pieces",
    serves: "3-4",
    description: "Fresh white mussels, cleaned and ready to cook. Excellent for steaming or making seafood pasta.",
    inStock: true,
  },
  {
    id: "11",
    name: "Surmai Fillets",
    price: 549,
    originalPrice: 699,
    image: "/surmai-fillets.jpg",
    category: "marine",
    rating: 4.7,
    reviews: 267,
    weight: "600g",
    pieces: "4-5 fillets",
    serves: "3-4",
    description: "Fresh Surmai (King Mackerel) fillets, boneless and skinless. Ideal for Indian curries and tandoori preparations.",
    inStock: true,
    badge: "Popular",
  },
  {
    id: "12",
    name: "Baby Lobster",
    price: 1299,
    originalPrice: 1599,
    image: "/baby-lobster.jpg",
    category: "shell",
    rating: 4.8,
    reviews: 156,
    weight: "300g",
    pieces: "2 pieces",
    serves: "2",
    description: "Tender baby lobsters, perfect for special occasions. Great for grilling with butter and garlic.",
    inStock: true,
    badge: "Luxury",
  },
]

export const recipes = [
  {
    id: "1",
    name: "Goan Fish Curry",
    image: "/goan-fish-curry.jpg",
    time: "45 mins",
    difficulty: "Medium",
    ingredients: ["Pomfret 500g", "Coconut Milk", "Tamarind", "Red Chilies", "Garlic"],
    steps: [
      "Clean and marinate the fish with salt and turmeric",
      "Grind coconut with spices to make masala paste",
      "Cook the paste in oil until aromatic",
      "Add tamarind water and bring to boil",
      "Add fish pieces and simmer for 15 minutes",
    ],
    video: "https://example.com/video",
  },
  {
    id: "2",
    name: "Butter Garlic Prawns",
    image: "/butter-garlic-prawns.jpg",
    time: "25 mins",
    difficulty: "Easy",
    ingredients: ["Prawns 500g", "Butter", "Garlic", "Lemon", "Parsley"],
    steps: [
      "Clean and devein prawns",
      "Sauté garlic in butter until golden",
      "Add prawns and cook on high heat",
      "Season with salt, pepper, and lemon juice",
      "Garnish with fresh parsley",
    ],
    video: "https://example.com/video2",
  },
  {
    id: "3",
    name: "Bengali Fish Curry",
    image: "/bengali-fish-curry-mustard.jpg",
    time: "40 mins",
    difficulty: "Medium",
    ingredients: ["Rohu 500g", "Mustard Paste", "Green Chilies", "Turmeric", "Mustard Oil"],
    steps: [
      "Marinate fish with salt and turmeric",
      "Lightly fry the fish pieces",
      "Make a paste of mustard seeds",
      "Cook mustard paste in oil",
      "Add water, fish, and simmer until done",
    ],
    video: "https://example.com/video3",
  },
]

export const testimonials = [
  {
    id: "1",
    name: "Priya Sharma",
    avatar: "/indian-woman-portrait.png",
    rating: 5,
    text: "The quality of fish is amazing! Always fresh and delivered on time. My family loves the pomfret.",
    location: "Mumbai",
  },
  {
    id: "2",
    name: "Rahul Menon",
    avatar: "/indian-man-portrait.png",
    rating: 5,
    text: "Best prawns I have ever ordered online. Cleaned perfectly and tastes so fresh!",
    location: "Bangalore",
  },
  {
    id: "3",
    name: "Anjali Patel",
    avatar: "/indian-woman-smiling.png",
    rating: 4,
    text: "Great service and quality. The combo packs are perfect for family gatherings.",
    location: "Chennai",
  },
]

export const faqs = [
  {
    question: "How fresh is your seafood?",
    answer:
      "All our seafood is sourced directly from fishermen and delivered within 24-48 hours of catch. We maintain cold chain throughout the delivery process.",
  },
  {
    question: "What are your delivery timings?",
    answer: "We deliver between 7 AM to 9 PM. You can choose your preferred time slot during checkout.",
  },
  {
    question: "Do you offer cleaning services?",
    answer: "Yes! All our fish and seafood come cleaned and ready to cook. You can choose your preferred cut style.",
  },
  {
    question: "What is your return policy?",
    answer:
      "If you are not satisfied with the quality, we offer 100% refund or replacement. Just contact us within 2 hours of delivery.",
  },
  {
    question: "Which areas do you deliver to?",
    answer:
      "We currently deliver to all major cities including Mumbai, Delhi, Bangalore, Chennai, Kolkata, Hyderabad, and Pune.",
  },
]
